### ISSUE TITLE
fix: Dependencies on paths won't be resolved

### ISSUE THREAD

**Issue by CodeDoctorDE** [VeryGoodOpenSource/dart_frog#304]
**Description**

If I use path dependencies, the project does not build.

**Steps To Reproduce**

1. Create a new project named `shared`
2. Open the `pubspec.yaml` in the server project
3. Insert
  ```yaml
    dependencies:
  dart_frog: ^0.1.0
  shared:
    path: ../shared
  ```
5. See error when running `dart_frog build`

**Expected Behavior**

A successful build.

**Screenshots**

\-

**Additional Context**

\-

**Comment by felangel** [comment]
Hi @CodeDoctorDE 👋 
Thanks for opening an issue and sorry for the delayed response! I plan to address this shortly, sorry for the inconvenience!

**Comment by CodeDoctorDE** [comment]
Hmm,
I created a new project but this error occurs again:
```
✓ Bundling sources (0.4s)
All path dependencies must be within the project.
External path dependencies detected:
  • shared from ../shared
✓ Installing dependencies (0.4s)
Because flow_server depends on shared from path which doesn't exist (could not find package shared at "../shared"), version solving failed.


Created a production build!

Start the production server by running:

dart build/bin/server.dart
```

I used
```yaml
dependencies:
  shared:
    path: ../shared
```

and all classes will be detected by dart.
