### ISSUE TITLE
canot start my project

### ISSUE THREAD

**Issue by bobwatcherx** [VeryGoodOpenSource/dart_frog#396]
i have problem . i use root , but get message error like this . 
MY DART VERSION:
📎
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"

root@ubuntux-Lenovo-V145-14AST:/home/ubuntux/belajar/dartapp/proj# dart_frog dev
```
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
✓ Running on http://localhost:8080 (5.5s)
Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
```

**Comment by felangel** [comment]
Hi @bobwatcherx 👋 
Thanks for opening an issue!

It looks like you are running `dart_frog dev` as a root user which is not recommended. This is working as expected and is consistent with how the dart/flutter tooling works.

Closing for now since there are no actionable next steps but feel free to comment with any follow-up questions and I'm happy to continue the conversation 👍

**Comment by bobwatcherx** [comment]
I no longer use root

but there is a problem running it

ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ dart_frog dev
⠏ Serving... (0.7s)Unable to execute hook: pre_gen.dart.
Error: Type 'RouteConfiguration' not found.
  RouteConfiguration configuration,

**Comment by felangel** [comment]
> I no longer use root
> 
> but there is a problem running it
> 
> ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ dart_frog dev ⠏ Serving... (0.7s)Unable to execute hook: pre_gen.dart. Error: Type 'RouteConfiguration' not found. RouteConfiguration configuration,

Can you provide reproduction steps? How did you install Dart?

**Comment by bobwatcherx** [comment]
i installed darts for flutter
with snap on ubuntu
`snap install flutter --classic`
```
ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ which dart
sh: 0: getcwd() failed: No such file or directory
/snap/bin/dart
```
**info**
dart_frog version :
0.2.2
Dart SDK version: 2.18.2 (stable)
**my pubspec.yaml**
```
name: dartfrog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
```
