### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by mrgnhnt96** [VeryGoodOpenSource/dart_frog#460]
**Description**

I am getting a warning in the console when running `dart_frog dev` from some of my generated code.

```console
dart_frog dev --verbose

[meta] dart_frog_cli 0.3.1
[codegen] running pre-gen...
⠙ Serving... (82ms)[codegen] running generate...
[codegen] complete.
[process] dart --enable-vm-service .dart_frog/server.dart
✓ Running on http://localhost:8080 (0.1s)
The Dart VM service is listening on http://127.0.0.1:8181/LKaUCcJtu-M=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/LKaUCcJtu-M=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FLKaUCcJtu-M%3D%2Fws
packages/domain/lib/models/user.g.dart:70:20: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
          ? _value.id!
                   ^
[process] killing process...
[process] process.kill()...
[process] killing process complete.
[process] exit(1)
```

**Steps To Reproduce**

1. Add dependencies `copy_with_extension`, `copy_with_extension_gen` (dev), `build_runner` (dev)
2. Create a basic dart object
   a. Add the `@CopyWith()` annotation
   b. Add a field `final String id`
3. Run build_runner
3. Run `dart_frog dev`

**Expected Behavior**

I'd expect for this warning to be omitted. I've added in the analysis_options to exclude generated files from the linter

**Screenshots**

```yaml
# analyis_options.yaml

include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
linter:
  rules:
    file_names: false
```

**Additional Context**

```yaml
# pubspec.yaml in `packages/domain`

name: domain
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  autoequal: ^0.5.1
  copy_with_extension: ^5.0.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

scripts: ../../derry.yaml
```
