### ISSUE TITLE
docs: update pubspec.yaml from web_socket example to use Dart 3

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#725]
**Description**

The `web_socket` tutorial, found [here](https://dartfrog.vgv.dev/docs/tutorials/web_socket_counter). Has the following `pubspec.yaml` example:

```yaml
name: example
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.0.0
```

The tutorial should be updated to use Dart 3.
